name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: frontendms
  IMAGE_TAG: ${{ github.run_number }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Build the Docker image
        run: docker build . --file Dockerfile --tag camilodev/frontendms:${{ secrets.MAJOR }}.${{ env.IMAGE_TAG }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push to DockerHub
        run: docker push camilodev/frontendms:${{ secrets.MAJOR }}.${{ env.IMAGE_TAG }}
      - name: run number with offset
        run: |
          echo ::set-env name=GITHUB_RUN_NUMBER_WITH_OFFSET::$(($IMAGE_TAG-1))
      - run: echo $GITHUB_RUN_NUMBER_WITH_OFFSET
  staging:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
            docker rm -f frontendms
            docker run -d -p 3000:3000 --name frontendms camilodev/frontendms:${{ secrets.MAJOR }}.${{ env.IMAGE_TAG }}
          host: ${{ secrets.SSH_HOST }}
          user: root
          key: ${{ secrets.SSH_KEY}}